#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then


    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi
# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi



while true; do
	sleeptime=20s
	mem=`free -m | grep '^Mem' | awk '{print "scale=3; " $3"/"$2"*100"}' | bc`
	echo $mem | grep '\.*0$' > /dev/null && mem=`echo $mem | sed -e 's/0*$//g' |sed 's/\.$//g'` 

	cpu=`top -bn 1 | grep '^%Cpu' | tr -d 'usy,' | awk '{print $2'+'$3}'|bc`

	bat=`acpi | cut -d ',' -f2 | cut -d ' ' -f2`

	xsetroot -name "MEM ${mem}%| CPU ${cpu}%| BAT ${bat}| $( date +"%R" )"
	
	test ${mem} -ge 50 || test ${cpu} -ge 50 && sleeptime=5s
	test ${mem} -ge 70 || test ${cpu} -ge 70 && sleeptime=3s

	sleep $sleeptime
done &

cd $HOME

exec dwm
